package concessionario.view;

public enum TipoEvento {
    
    ANAGRAFICA_CLIENTI,
    GESTIONE_AUTO,
    AGGIORNA_VENDITE,
    ANAGRAFICA_CLIENTI_APERTA,
    GESTIONE_AUTO_APERTA,
    REGISTRA_CLIENTI,
    CERCA_CLIENTI,
    CERCA_CLIENTI_CF,
    CERCA_AUTO,
    CERCA_AUTO_USATE,
    MOSTRA_PREVENTIVO,
    CONCLUDI_VENDITA
}
